# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import backend as K

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive


# Import Files

In [2]:
pd.set_option("display.precision", 15)
data_user = pd.read_csv('data_user_gabungan.csv')
data_shelter = pd.read_excel('shelter.xlsx')

In [6]:
data_user.head()

Unnamed: 0           latitude            longitude jenis_hewan  \
0           0 -8.815969433257180  115.160016269129997      Anjing   
1           1 -8.819023510886071  115.162463026801007      Anjing   
2           2 -8.824240739105679  115.165508328648997      Anjing   
3           3 -8.810656715085271  115.175930986319003      Anjing   
4           4 -8.809078416277130  115.161708869129001      Anjing   

   nama_shelter  
0  ILUH SHELTER  
1  ILUH SHELTER  
2  ILUH SHELTER  
3  ILUH SHELTER  
4  ILUH SHELTER

In [5]:
data_shelter.head()

nama_shelter  \
0                                   Adin Guppy   
1                          Cat Shelter Cirebon   
2                          Rezcha animal cargo   
3                                     TamBonNa   
4  Animal lover jogja Shelter “ fortune Life “   

                                      alamat_shelter          latitude  \
0  Gg. Kancil I No.14, Jagabaya II, Kec. Way Hali... -5.39559037005795   
1  Komplek PDK, Jl. Perjuangan No.Blok H, Sunyara... -6.72918640211714   
2  Jl. Gedung Batu Utara I No.16, RT.02/RW.06, Ng... -6.99025117213540   
3  Blk. D-C1, Wonorejo, Kec. Rungkut, Surabaya, J... -7.30871717914754   
4  Pucangan, Widodomartani, Kec. Ngemplak, Kabupa... -7.68159787622054   

             longitude jenis_hewan  
0  105.268503514949998     Lainnya  
1  108.532242823798995      Kucing  
2  110.405206112146999     Lainnya  
3  112.818391621615007      Anjing  
4  110.448696050901006      Anjing

# Modifying Dataframes

In [141]:
# Create function to seperate latitude and longitude values
def latitude_value(row):
  return row.replace(' ','').split(',')[0]

def longitude_value(row):
  return row.replace(' ','').split(',')[1]

In [ ]:
# Apply the function to seperate latitude and longitude values
data_user['longitude'] = data_user['latitude'].apply(lambda row: longitude_value(row))
data_user['latitude'] = data_user['latitude'].apply(lambda row: latitude_value(row))

In [ ]:
# Restructuring the order of columns
data_user = data_user[['alamat_user','latitude','longitude','jenis_hewan','nama_shelter']]

In [ ]:
data_shelter = data_shelter.drop(columns=['Unnamed: 5'])
data_shelter = data_shelter.dropna()

In [7]:
data_shelter = data_shelter[['alamat_shelter','latitude','longitude','jenis_hewan','nama_shelter']]

In [50]:
# Convert 'latitude' and 'longitude' column into float type
data_user = data_user.astype({'latitude': np.float32, 'longitude': np.float32})

In [51]:
# Convert 'nama_shelter' into numerical

## Define/Initialize the Label Encoder
le_user = LabelEncoder()

## Fit the Label Encoder and use it to transform the target ('nama_shelter' column)
data_user['nama_shelter'] = le_user.fit_transform(data_user['nama_shelter'])

In [52]:
data_user.head()

Unnamed: 0           latitude            longitude jenis_hewan  \
0           0 -8.815969467163086  115.160018920898438      Anjing   
1           1 -8.819023132324219  115.162460327148438      Anjing   
2           2 -8.824240684509277  115.165512084960938      Anjing   
3           3 -8.810656547546387  115.175933837890625      Anjing   
4           4 -8.809078216552734  115.161712646484375      Anjing   

   nama_shelter  
0            77  
1            77  
2            77  
3            77  
4            77

In [53]:
data_shelter.head()

alamat_shelter          latitude  \
0  Gg. Kancil I No.14, Jagabaya II, Kec. Way Hali... -5.39559037005795   
1  Komplek PDK, Jl. Perjuangan No.Blok H, Sunyara... -6.72918640211714   
2  Jl. Gedung Batu Utara I No.16, RT.02/RW.06, Ng... -6.99025117213540   
3  Blk. D-C1, Wonorejo, Kec. Rungkut, Surabaya, J... -7.30871717914754   
4  Pucangan, Widodomartani, Kec. Ngemplak, Kabupa... -7.68159787622054   

             longitude jenis_hewan  \
0  105.268503514949998     Lainnya   
1  108.532242823798995      Kucing   
2  110.405206112146999     Lainnya   
3  112.818391621615007      Anjing   
4  110.448696050901006      Anjing   

                                  nama_shelter  
0                                   Adin Guppy  
1                          Cat Shelter Cirebon  
2                          Rezcha animal cargo  
3                                     TamBonNa  
4  Animal lover jogja Shelter “ fortune Life “

In [54]:
data_user_2 = data_user.copy()

In [55]:
data_user_2 = data_user_2[['latitude','longitude','jenis_hewan','nama_shelter']]

In [56]:
data_user_2

latitude            longitude jenis_hewan  nama_shelter
0     -8.815969467163086  115.160018920898438      Anjing            77
1     -8.819023132324219  115.162460327148438      Anjing            77
2     -8.824240684509277  115.165512084960938      Anjing            77
3     -8.810656547546387  115.175933837890625      Anjing            77
4     -8.809078216552734  115.161712646484375      Anjing            77
...                  ...                  ...         ...           ...
34897 -0.900111079216003  119.859542846679688     Lainnya            72
34898 -0.899459779262543  119.854179382324219     Lainnya            72
34899 -0.898308813571930  119.856842041015625     Lainnya            72
34900 -0.898099362850189  119.859321594238281     Lainnya            72
34901 -0.900677919387817  119.856315612792969     Lainnya            72

[34902 rows x 4 columns]

# Split the Dataset into Train and Test

In [57]:
# Split the data into train and test
train, test = train_test_split(data_user_2, test_size=0.1, random_state=0)

In [67]:
# Split train data into train and validation data
train, validation = train_test_split(train, test_size=0.1, random_state=0)

In [68]:
print('Number of data for training:', len(train), 'rows')
print('Number of data for validating:', len(validation), 'rows')
print('Number of data for testing:', len(test), 'rows')

Number of data for training: 28269 rows
Number of data for validating: 3142 rows
Number of data for testing: 3491 rows


# Preparing the Dataset for input to the Deep Learning Model

In [69]:
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('nama_shelter')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe),labels))

  if shuffle == True:
    ds = ds.shuffle(buffer_size=len(dataframe))

  ds = ds.batch(batch_size=batch_size)

  return ds

In [70]:
# Define the batch_size to be used
batch_size = 64

# Converting the train and test datframes into tfds dataset
train_ds = df_to_dataset(train, batch_size=batch_size)
validation_ds = df_to_dataset(validation, shuffle=False)
test_ds = df_to_dataset(test, shuffle=False)

In [71]:
output_num = data_user_2['nama_shelter'].nunique()
print(output_num)

212


## Take a Look at Input Pipeline

In [72]:
# Take a look at a single batch
for feature, label in train_ds.take(1):
  print('Every feature:', list(feature.keys()))
  print('A batch of ages:', feature['jenis_hewan'])
  print('A batch of targets:', label)

Every feature: ['latitude', 'longitude', 'jenis_hewan']
A batch of ages: tf.Tensor(
[b'Lainnya' b'Lainnya' b'Anjing' b'Lainnya' b'Anjing' b'Kucing' b'Kucing'
 b'Lainnya' b'Anjing' b'Lainnya' b'Lainnya' b'Anjing' b'Kucing' b'Kucing'
 b'Kucing' b'Anjing' b'Kucing' b'Anjing' b'Lainnya' b'Lainnya' b'Lainnya'
 b'Anjing' b'Lainnya' b'Kucing' b'Kucing' b'Lainnya' b'Lainnya' b'Kucing'
 b'Kucing' b'Kucing' b'Lainnya' b'Kucing' b'Lainnya' b'Lainnya' b'Kucing'
 b'Anjing' b'Lainnya' b'Lainnya' b'Lainnya' b'Lainnya' b'Anjing'
 b'Lainnya' b'Lainnya' b'Lainnya' b'Lainnya' b'Anjing' b'Lainnya'
 b'Anjing' b'Anjing' b'Lainnya' b'Anjing' b'Kucing' b'Kucing' b'Kucing'
 b'Lainnya' b'Lainnya' b'Lainnya' b'Kucing' b'Lainnya' b'Lainnya'
 b'Lainnya' b'Anjing' b'Anjing' b'Lainnya'], shape=(64,), dtype=string)
A batch of targets: tf.Tensor(
[199  30  22 142 186 100  67 151 197 181  17 176 152 112  68 197 190 110
 114   1 166  77 207 182   8   7  91  32  56  67  71 204  49 117 205  66
   1 147  65 181 134  49 169

# Create Several Types of Feature Columns

In [73]:
feature_columns = []

# Numeric columns: 'latitude','longitude'
numeric_columns = ['latitude','longitude']

for col in numeric_columns:
  numeric_feature_column = tf.feature_column.numeric_column(col)
  feature_columns.append(numeric_feature_column)

# Categorical columns: 'jenis_hewan'
jenis_hewan = tf.feature_column.categorical_column_with_vocabulary_list('jenis_hewan',['Kucing','Anjing','Lainnya'])
jenis_hewan_one_hot = tf.feature_column.indicator_column(jenis_hewan)
feature_columns.append(jenis_hewan_one_hot)

## Create a Feature Layer

In [74]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

# Model

In [75]:
K.clear_session()

In [76]:
model = tf.keras.Sequential([
    feature_layer,
    tf.keras.layers.Dense(units=128, activation='relu'),
    tf.keras.layers.Dense(units=128, activation='relu'),
    tf.keras.layers.Dense(units=256, activation='relu'),
    tf.keras.layers.Dense(units=output_num, activation='softmax')
])

In [77]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy']) 

In [78]:
model.fit(train_ds, validation_data=validation_ds, epochs=1000)

Epoch 1/1000


442/442 [==============================] - ETA: 0s - loss: 5.6066 - accuracy: 0.0221WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor. Received: inputs={'latitude': <tf.Tensor 'IteratorGetNext:1' shape=(None,) dtype=float32>, 'longitude': <tf.Tensor 'IteratorGetNext:2' shape=(None,) dtype=float32>, 'jenis_hewan': <tf.Tensor 'IteratorGetNext:0' shape=(None,) dtype=string>}. Consider rewriting this model with the Functional API.


442/442 [==============================] - 7s 9ms/step - loss: 5.6066 - accuracy: 0.0221 - val_loss: 5.0077 - val_accuracy: 0.0439
Epoch 2/1000
442/442 [==============================] - 3s 7ms/step - loss: 4.7931 - accuracy: 0.0424 - val_loss: 4.5900 - val_accuracy: 0.0541
Epoch 3/1000
442/442 [==============================] - 3s 7ms/step - loss: 4.4202 - accuracy: 0.0621 - val_loss: 4.2688 - val_accuracy: 0.0675
Epoch 4/1000
442/442 [==============================] - 3s 7ms/step - loss: 4.1361 - accuracy: 0.0793 - val_loss: 4.0087 - val_accuracy: 0.0958
Epoch 5/1000
442/442 [==============================] - 4s 9ms/step - loss: 3.8834 - accuracy: 0.0959 - val_loss: 3.7541 - val_accuracy: 0.1044
Epoch 6/1000
442/442 [==============================] - 4s 8ms/step - loss: 3.6492 - accuracy: 0.1200 - val_loss: 3.5245 - val_accuracy: 0.1123
Epoch 7/1000
442/442 [==============================] - 4s 8ms/step - loss: 3.4265 - accuracy: 0.1426 - val_loss: 3.3106 - val_accuracy: 0.1604
Epoch

In [79]:
model.evaluate(test_ds)

110/110 [==============================] - 1s 2ms/step - loss: 0.4302 - accuracy: 0.8141


[0.43016350269317627, 0.8140934109687805]

In [80]:
for key, value in test_ds.take(1):
  print(key, value)

{'latitude': <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([-6.3736353 , -3.9362    ,  1.7379347 , -5.1332846 , -6.4674215 ,
       -6.1585917 ,  1.3990443 , -8.792274  ,  3.307397  , -0.2199044 ,
       -7.6706953 ,  1.4684479 , -8.834262  , -0.96287304,  3.598694  ,
       -8.69965   ,  3.5972466 ,  2.9712791 ,  0.57796365, -6.2786064 ,
       -5.164077  ,  0.4968608 , -2.9594033 , -8.433937  , -5.210493  ,
       -8.698954  , -7.437653  , -6.1069965 , -7.635421  , -6.9000463 ,
       -5.3778553 , -3.3185346 ], dtype=float32)>, 'longitude': <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([106.70298 , 102.3761  ,  98.7917  , 119.41949 , 106.74858 ,
       106.71396 ,  99.26049 , 115.17021 , 117.60614 , 100.637505,
       112.904724, 124.82861 , 115.17821 , 100.39839 ,  98.50708 ,
       115.181   ,  98.75516 ,  99.07892 , 123.03469 , 106.816185,
       119.45993 , 101.38302 , 104.77186 , 115.29434 , 119.43933 ,
       115.23666 , 111.4217  , 106.6951  , 111.5407  , 107.652

# Test Input Pipeline from User

In [59]:
-8.783392133495186, 115.17229372758489

(-8.79332020622897, 115.16116080903728)

In [30]:
# Create input API
latitude_input = float(input('Masukkan nilai latitude: '))
longitude_input = float(input('Masukkan nilai longitude: '))
jenis_hewan_input = str(input('Masukkan jenis hewan yang diminati: '))

In [81]:
# Create dataframe to contain user's inputs
df_for_test_predict = pd.DataFrame(data={'latitude':[latitude_input], 
                                         'longitude':[longitude_input], 
                                         'jenis_hewan':[jenis_hewan_input]})

In [82]:
df_for_test_predict

latitude            longitude jenis_hewan
0 -8.783392133495186  115.172293727584886      Anjing

In [83]:
# Create function to convert user's inputs dataframe into tensorflow ds
def df_user_input_to_ds(df_user):
  df_user = df_user.copy()
  ds = tf.data.Dataset.from_tensor_slices(dict(df_user))
  ds = ds.batch(1)
  return ds

In [84]:
predict_ds = df_user_input_to_ds(df_for_test_predict)

In [85]:
# Model prediction
model_prediction = model.predict(predict_ds)

1/1 [==============================] - 0s 282ms/step


In [86]:
model_prediction

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 6.7611232e-05, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.3019428e-22, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        6.2314700e-04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        7.7019059e-14, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e

In [87]:
prediction_result = model_prediction[0]

In [88]:
# Get the prediction result from model
prediction_result

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 6.7611232e-05, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 2.3019428e-22, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       6.2314700e-04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       7.7019059e-14, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e

In [89]:
# Get the highest index of prediction_index array
highest_prediction_index = np.argmax(prediction_result)

In [90]:
highest_prediction_index

187

In [91]:
# Give the result back to the user
output_to_user = le_user.inverse_transform([highest_prediction_index])

In [92]:
output_to_user

array([187])

# Exporting to TFLite

In [93]:
export_dir = 'saved_model/1/'
tf.saved_model.save(model, export_dir=export_dir)

INFO:tensorflow:Assets written to: saved_model/1/assets


INFO:tensorflow:Assets written to: saved_model/1/assets


In [94]:
converter = tf.lite.TFLiteConverter.from_saved_model(export_dir)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_model = converter.convert();

In [96]:
import pathlib

tflite_model_file = pathlib.Path('saved_model/1//model.tflite')
tflite_model_file.write_bytes(tflite_model)

115712