# Import Libraries

In [ ]:
# Import Libraries
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import backend as K

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Import Files

In [ ]:
pd.set_option("display.precision", 15)
data_user_helmi = pd.read_csv('/content/drive/MyDrive/Data Capstone Personal/data_capstone - helmi_data_user2.csv')
data_user_ivan = pd.read_csv('/content/drive/MyDrive/Data Capstone Personal/data_capstone - ivan_data_user2.csv')
data_user_joshia = pd.read_csv('/content/drive/MyDrive/Data Capstone Personal/data_capstone - joshia_data_user.csv')

In [ ]:
data_user_helmi = data_user_helmi[['latitude','longitude','jenis_hewan','nama_shelter']]
data_user_ivan = data_user_ivan[['latitude','longitude','jenis hewan','nama shelter']]
data_user_ivan = data_user_ivan.rename(columns={'jenis hewan':'jenis_hewan', 'nama shelter':'nama_shelter'})
data_user_joshia = data_user_joshia[['latitude','longitude','jenis_hewan','nama_shelter']]

In [ ]:
data_user_helmi.head()

latitude            longitude jenis_hewan  nama_shelter
0 -8.815969433257180  115.160016269129997      Anjing  ILUH SHELTER
1 -8.819023510886071  115.162463026801007      Anjing  ILUH SHELTER
2 -8.824240739105679  115.165508328648997      Anjing  ILUH SHELTER
3 -8.810656715085271  115.175930986319003      Anjing  ILUH SHELTER
4 -8.809078416277130  115.161708869129001      Anjing  ILUH SHELTER

In [ ]:
data_user_ivan.head()

latitude            longitude jenis_hewan   nama_shelter
0 -6.988513643  110.471941900000004      Kucing  Adit Pet'shop
1 -6.989197344  110.471735699999996      Kucing  Adit Pet'shop
2 -6.988338617  110.470171399999998      Kucing  Adit Pet'shop
3 -6.988850935  110.471989199999996      Kucing  Adit Pet'shop
4 -6.988906558  110.471974200000005      Kucing  Adit Pet'shop

In [ ]:
data_user_joshia.head()

latitude            longitude jenis_hewan      nama_shelter
0  -0.874937578472888  131.304827292763008      Kucing  MAUZAN CAT HOUSE
1  -0.874842412372507  131.296863143223987      Kucing  MAUZAN CAT HOUSE
2  -0.875888557588894  131.298583116906002      Kucing  MAUZAN CAT HOUSE
3  -0.878784102768380  131.294561881530001      Kucing  MAUZAN CAT HOUSE
4  -0.876762910135965  131.307460403734012      Kucing  MAUZAN CAT HOUSE

In [ ]:
print('The number of rows in data Helmi: ', len(data_user_helmi))
print('The number of rows in data Ivan: ', len(data_user_ivan))
print('The number of rows in data Joshia: ', len(data_user_joshia))
print('Total number of rows: ', len(data_user_helmi)+len(data_user_ivan)+len(data_user_joshia))

The number of rows in data Helmi:  11440
The number of rows in data Ivan:  12672
The number of rows in data Joshia:  10791
Total number of rows:  34903


# Modifying Dataframes

In [ ]:
# Combine 3 dataframes into one single dataframe
data_user_final = pd.concat([data_user_helmi, data_user_ivan, data_user_joshia])

In [ ]:
data_user_final

latitude            longitude jenis_hewan    nama_shelter
0       -8.81596943325718  115.160016269129997      Anjing    ILUH SHELTER
1      -8.819023510886071  115.162463026801007      Anjing    ILUH SHELTER
2      -8.824240739105679  115.165508328648997      Anjing    ILUH SHELTER
3      -8.810656715085271  115.175930986319003      Anjing    ILUH SHELTER
4       -8.80907841627713  115.161708869129001      Anjing    ILUH SHELTER
...                   ...                  ...         ...             ...
10786  -0.900111050129143  119.859541447195994     Lainnya  Herli pet shop
10787  -0.899459787625817  119.854179654524998     Lainnya  Herli pet shop
10788  -0.898308810227713  119.856843345181005     Lainnya  Herli pet shop
10789  -0.898099357412485  119.859320431257999     Lainnya  Herli pet shop
10790  -0.900677946173515  119.856315802043994     Lainnya  Herli pet shop

[34903 rows x 4 columns]

In [ ]:
latitude_not_float = data_user_final[data_user_final['latitude'].map(lambda x: isinstance(x, float)) == False]

In [ ]:
latitude_not_float

latitude            longitude jenis_hewan      nama_shelter
0      -0.874937578472888  131.304827292763008      Kucing  MAUZAN CAT HOUSE
1      -0.874842412372507  131.296863143223987      Kucing  MAUZAN CAT HOUSE
2      -0.875888557588894  131.298583116906002      Kucing  MAUZAN CAT HOUSE
3      -0.878784102768380  131.294561881530001      Kucing  MAUZAN CAT HOUSE
4      -0.876762910135965  131.307460403734012      Kucing  MAUZAN CAT HOUSE
...                   ...                  ...         ...               ...
10786  -0.900111050129143  119.859541447195994     Lainnya    Herli pet shop
10787  -0.899459787625817  119.854179654524998     Lainnya    Herli pet shop
10788  -0.898308810227713  119.856843345181005     Lainnya    Herli pet shop
10789  -0.898099357412485  119.859320431257999     Lainnya    Herli pet shop
10790  -0.900677946173515  119.856315802043994     Lainnya    Herli pet shop

[10791 rows x 4 columns]

In [ ]:
# Check each column type
data_user_final.dtypes

latitude         object
longitude       float64
jenis_hewan      object
nama_shelter      int64
dtype: object

In [ ]:
data_user_final[data_user_final['latitude'] == '#ERROR!']

latitude           longitude jenis_hewan  nama_shelter
5979  #ERROR!  98.782381150394102      Anjing  Tata Petshop

In [ ]:
data_user_final = data_user_final[data_user_final['latitude'] != '#ERROR!']

In [ ]:
# Convert 'latitude' and 'longitude' column into float type
data_user_final = data_user_final.astype({'latitude': np.float64, 'longitude': np.float64})

In [ ]:
data_user_final

latitude            longitude jenis_hewan    nama_shelter
0     -8.815969433257180  115.160016269129997      Anjing    ILUH SHELTER
1     -8.819023510886071  115.162463026801007      Anjing    ILUH SHELTER
2     -8.824240739105679  115.165508328648997      Anjing    ILUH SHELTER
3     -8.810656715085271  115.175930986319003      Anjing    ILUH SHELTER
4     -8.809078416277130  115.161708869129001      Anjing    ILUH SHELTER
...                  ...                  ...         ...             ...
10786 -0.900111050129143  119.859541447195994     Lainnya  Herli pet shop
10787 -0.899459787625817  119.854179654524998     Lainnya  Herli pet shop
10788 -0.898308810227713  119.856843345181005     Lainnya  Herli pet shop
10789 -0.898099357412485  119.859320431257999     Lainnya  Herli pet shop
10790 -0.900677946173515  119.856315802043994     Lainnya  Herli pet shop

[34902 rows x 4 columns]

In [ ]:
# Check the total number of unique shelter
num_shelter = data_user_final['nama_shelter'].nunique()

In [ ]:
num_shelter

212

In [ ]:
# Convert 'nama_shelter' into numerical

## Define/Initialize the Label Encoder
le_user = LabelEncoder()

## Fit the Label Encoder and use it to transform the target ('nama_shelter' column)
data_user_final['nama_shelter'] = le_user.fit_transform(data_user_final['nama_shelter'])

In [ ]:
data_user_final.head()

latitude            longitude jenis_hewan  nama_shelter
0 -8.815969433257180  115.160016269129997      Anjing            77
1 -8.819023510886071  115.162463026801007      Anjing            77
2 -8.824240739105679  115.165508328648997      Anjing            77
3 -8.810656715085271  115.175930986319003      Anjing            77
4 -8.809078416277130  115.161708869129001      Anjing            77

In [ ]:
# Some usual checks
print(max(data_user_final['nama_shelter']))
print(min(data_user_final['nama_shelter']))

211
0


# Split the Dataset into Train and Test

In [ ]:
# Split the data into train and test
train, test = train_test_split(data_user_final, test_size=0.1, random_state=0)

In [ ]:
# Split train data into train and validation data
train, validation = train_test_split(train, test_size=0.1, random_state=0)

In [ ]:
print('Number of data for training:', len(train), 'rows')
print('Number of data for validating:', len(validation), 'rows')
print('Number of data for testing:', len(test), 'rows')

Number of data for training: 28269 rows
Number of data for validating: 3142 rows
Number of data for testing: 3491 rows


In [ ]:
train

latitude            longitude jenis_hewan  nama_shelter
10082 -7.748098756314290  112.744240199819004     Lainnya           151
6442  -7.009690653000000  110.397800799999999     Lainnya           200
8647  -0.939671732211982  100.458648318441007      Kucing           182
5492  -5.170097912888870  119.467579219510000      Kucing           156
4588   1.680115086015750  101.449516919645006      Kucing            54
...                  ...                  ...         ...           ...
8496  -8.618324489187071  115.184870380210000      Kucing           192
2317   3.543763570611100   98.650441258405408     Lainnya           114
121   -6.990497222000000  110.471275599999998      Kucing             8
8572  -8.198364926624510  112.662320791168000      Kucing           206
7265  -7.768853547301480  113.202325225877999     Lainnya           207

[28269 rows x 4 columns]

# Preparing the Dataset for input to the Deep Learning Model

In [ ]:
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('nama_shelter')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe),labels))

  if shuffle == True:
    ds = ds.shuffle(buffer_size=len(dataframe))

  ds = ds.batch(batch_size=batch_size)

  return ds

In [ ]:
# Define the batch_size to be used
batch_size = 64

# Converting the train and test datframes into tfds dataset
train_ds = df_to_dataset(train, batch_size=batch_size)
validation_ds = df_to_dataset(validation, shuffle=False)
test_ds = df_to_dataset(test, shuffle=False)

## Take a Look at Input Pipeline

In [ ]:
# Take a look at a single batch
for feature, label in train_ds.take(1):
  print('Every feature:', list(feature.keys()))
  print('A batch of ages:', feature['jenis_hewan'])
  print('A batch of targets:', label)

Every feature: ['latitude', 'longitude', 'jenis_hewan']
A batch of ages: tf.Tensor(
[b'Lainnya' b'Lainnya' b'Kucing' b'Kucing' b'Kucing' b'Lainnya' b'Kucing'
 b'Lainnya' b'Anjing' b'Lainnya' b'Lainnya' b'Kucing' b'Kucing' b'Anjing'
 b'Lainnya' b'Lainnya' b'Lainnya' b'Kucing' b'Kucing' b'Lainnya' b'Kucing'
 b'Lainnya' b'Lainnya' b'Lainnya' b'Kucing' b'Lainnya' b'Kucing' b'Kucing'
 b'Kucing' b'Anjing' b'Kucing' b'Lainnya' b'Kucing' b'Kucing' b'Kucing'
 b'Anjing' b'Kucing' b'Kucing' b'Lainnya' b'Kucing' b'Kucing' b'Lainnya'
 b'Anjing' b'Lainnya' b'Lainnya' b'Lainnya' b'Lainnya' b'Lainnya'
 b'Kucing' b'Kucing' b'Lainnya' b'Kucing' b'Lainnya' b'Kucing' b'Kucing'
 b'Kucing' b'Lainnya' b'Lainnya' b'Kucing' b'Lainnya' b'Lainnya' b'Anjing'
 b'Lainnya' b'Lainnya'], shape=(64,), dtype=string)
A batch of targets: tf.Tensor(
[114  72 159  16 182 131 164  12 184 170 142 167 126  21  84  81  71  47
 135 199 211 169  25 172 160  13 164  16 143 185 104 147 104 192  96 175
  98  55  64 186 195  42 110 1

# Create Several Types of Feature Columns

In [ ]:
feature_columns = []

# Numeric columns: 'latitude','longitude'
numeric_columns = ['latitude','longitude']

for col in numeric_columns:
  numeric_feature_column = tf.feature_column.numeric_column(col)
  feature_columns.append(numeric_feature_column)

# Categorical columns: 'jenis_hewan'
jenis_hewan = tf.feature_column.categorical_column_with_vocabulary_list('jenis_hewan',['Kucing','Anjing','Lainnya'])
jenis_hewan_one_hot = tf.feature_column.indicator_column(jenis_hewan)
feature_columns.append(jenis_hewan_one_hot)

## Create a Feature Layer

In [ ]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

# Model

In [ ]:
# Some hyperparameters
output_num = data_user_final['nama_shelter'].nunique()
learning_rate=0.00001

In [ ]:
output_num

212

In [ ]:
K.clear_session()

In [ ]:
model = tf.keras.Sequential([
    feature_layer,
    tf.keras.layers.Dense(units=256, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(units=256, activation='relu'),
    # tf.keras.layers.Dropout(0.3),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(units=output_num, activation='softmax')
])

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy']) 

In [ ]:
model.fit(train_ds, validation_data=validation_ds, epochs=700)

Epoch 1/700


442/442 [==============================] - ETA: 0s - loss: 4.9289 - accuracy: 0.0362

442/442 [==============================] - 4s 6ms/step - loss: 4.9289 - accuracy: 0.0362 - val_loss: 4.2326 - val_accuracy: 0.0656
Epoch 2/700
442/442 [==============================] - 3s 6ms/step - loss: 3.6496 - accuracy: 0.1073 - val_loss: 3.1207 - val_accuracy: 0.1321
Epoch 3/700
442/442 [==============================] - 3s 6ms/step - loss: 2.8845 - accuracy: 0.1600 - val_loss: 2.8088 - val_accuracy: 0.1569
Epoch 4/700
442/442 [==============================] - 3s 6ms/step - loss: 2.6360 - accuracy: 0.1889 - val_loss: 2.6297 - val_accuracy: 0.1840
Epoch 5/700
442/442 [==============================] - 3s 6ms/step - loss: 2.4971 - accuracy: 0.2076 - val_loss: 2.5076 - val_accuracy: 0.1906
Epoch 6/700
442/442 [==============================] - 3s 6ms/step - loss: 2.4046 - accuracy: 0.2207 - val_loss: 2.3860 - val_accuracy: 0.2451
Epoch 7/700
442/442 [==============================] - 3s 6ms/step - loss: 2.3300 - accuracy: 0.2333 - val_loss: 2.3223 - val_accuracy: 0.2355
Epoch 8/700

In [ ]:
model.evaluate(test_ds)

38/38 [==============================] - 0s 1ms/step - loss: 0.4281 - accuracy: 0.8462


[0.4281049370765686, 0.8461538553237915]

In [ ]:
for key, value in test_ds.take(1):
  print(key, value)

{'latitude': <tf.Tensor: shape=(32,), dtype=float64, numpy=
array([-6.3763841 , -8.43199038,  5.58860533, -7.00041811, -7.00223899,
       -6.38915323, -8.56964615, -6.11122784, -8.54938675, -7.3454841 ,
       -8.53714108, -8.42165472, -8.42899145, -7.38456244, -8.79188744,
       -8.54048387, -8.20609525, -6.38255658,  0.55139645, -6.37712091,
       -6.38679255, -8.78686354, -6.3760374 , -8.41240566, -6.14997597,
       -8.63070982, -8.64433078, -7.77072181, -6.38195053, -6.24057961,
       -1.00818722,  0.57299531])>, 'longitude': <tf.Tensor: shape=(32,), dtype=float64, numpy=
array([106.70494561, 115.13159079,  95.36114168, 107.5685756 ,
       107.56549378, 106.68651877, 115.25496747, 106.69587391,
       115.26533814, 111.5112686 , 115.28210086, 115.27219495,
       115.02839363, 111.40694006, 115.15637282, 115.24712601,
       114.35048629, 106.70410075, 123.08103199, 106.70777984,
       106.68652994, 115.15012156, 106.70271317, 115.05776696,
       106.91827991, 115.21432046,

# Test Input Pipeline from User

In [ ]:
-6.3062319187001386, 106.76705569923135

(-8.79332020622897, 115.16116080903728)

In [ ]:
# Create input API
latitude_input = float(input('Masukkan nilai latitude: '))
longitude_input = float(input('Masukkan nilai longitude: '))
jenis_hewan_input = str(input('Masukkan jenis hewan yang diminati: '))

In [ ]:
# Create dataframe to contain user's inputs
df_for_test_predict = pd.DataFrame(data={'latitude':[latitude_input], 
                                         'longitude':[longitude_input], 
                                         'jenis_hewan':[jenis_hewan_input]})

In [ ]:
df_for_test_predict

latitude            longitude jenis_hewan
0 -6.306231918700139  106.767055699231349      Kucing

In [ ]:
# Create function to convert user's inputs dataframe into tensorflow ds
def df_user_input_to_ds(df_user):
  df_user = df_user.copy()
  ds = tf.data.Dataset.from_tensor_slices(dict(df_user))
  ds = ds.batch(1)
  return ds

In [ ]:
predict_ds = df_user_input_to_ds(df_for_test_predict)

In [ ]:
# Model prediction
model_prediction = model.predict(predict_ds)

1/1 [==============================] - 0s 79ms/step


In [ ]:
prediction_result = model_prediction[0]

In [ ]:
# Get the prediction result from model
prediction_result

array([3.9214319e-24, 2.4679459e-03, 0.0000000e+00, 3.1579078e-28,
       0.0000000e+00, 2.1027393e-19, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.9934566e-12,
       2.0331258e-15, 1.2084644e-27, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 3.0984852e-04, 1.5014702e-27,
       1.2804684e-29, 1.7264182e-13, 2.9896373e-01, 0.0000000e+00,
       0.0000000e+00, 8.3366518e-22, 0.0000000e+00, 1.0868048e-32,
       8.3713153e-13, 2.6312795e-31, 3.7586386e-16, 2.4104477e-12,
       8.8824265e-08, 4.8554020e-23, 0.0000000e+00, 0.0000000e+00,
       6.9875264e-34, 0.0000000e+00, 1.0624112e-24, 1.3393215e-29,
       1.8760557e-01, 8.3551918e-27, 1.1441056e-15, 1.0305414e-17,
       6.1798054e-32, 1.2165172e-19, 1.2257608e-24, 1.5225417e-17,
       2.3556311e-18, 1.0958374e-27, 3.1601901e-25, 0.0000000e+00,
       2.0708164e-21, 3.2924169e-01, 0.0000000e+00, 1.6346082e

In [ ]:
# Get the highest index of prediction_index array
highest_prediction_index = np.argmax(prediction_result)

In [ ]:
highest_prediction_index

57

In [ ]:
# Give the result back to the user
output_to_user = le_user.inverse_transform([highest_prediction_index])

In [ ]:
output_to_user

array(['Omah Ucing'], dtype=object)

In [ ]:
# Download dataset
data_user_final.to_csv('data_user_gabungan.csv')

# Test

In [ ]:
test = data_user['latitude'].iloc[0].replace(' ','').split(',')
test

['-0.8794857742573828', '131.2980475555453']

In [ ]:
data_user_copy = data_user.copy()

In [ ]:
data_user_copy.head()

jenis_hewan                                        alamat_user  \
0      Kucing  Malaingkedi, Sorong Utara, Malaingkedi, Kec. S...   
1      Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
2      Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
3      Kucing  Malaingkedi, Sorong Manoi, Sorong City, West P...   
4      Kucing  Jl. Tj. Dofior, Malaingkedi, Kec. Sorong Utara...   

                                  latitude  longitude      nama_shelter  
0   -0.8794857742573828, 131.2980475555453        NaN  MAUZAN CAT HOUSE  
1    -0.878624210533688, 131.2977266651048        NaN  MAUZAN CAT HOUSE  
2   -0.8780682204151269, 131.2979108467057        NaN  MAUZAN CAT HOUSE  
3  -0.8774857465062342, 131.29741346457152        NaN  MAUZAN CAT HOUSE  
4  -0.8813631850780076, 131.30094486842142        NaN  MAUZAN CAT HOUSE

In [ ]:
data_user_copy = data_user_copy.drop(columns=['longitude'])

In [ ]:
data_user_copy.head()

jenis_hewan                                        alamat_user  \
0      Kucing  Malaingkedi, Sorong Utara, Malaingkedi, Kec. S...   
1      Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
2      Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
3      Kucing  Malaingkedi, Sorong Manoi, Sorong City, West P...   
4      Kucing  Jl. Tj. Dofior, Malaingkedi, Kec. Sorong Utara...   

                                  latitude      nama_shelter  
0   -0.8794857742573828, 131.2980475555453  MAUZAN CAT HOUSE  
1    -0.878624210533688, 131.2977266651048  MAUZAN CAT HOUSE  
2   -0.8780682204151269, 131.2979108467057  MAUZAN CAT HOUSE  
3  -0.8774857465062342, 131.29741346457152  MAUZAN CAT HOUSE  
4  -0.8813631850780076, 131.30094486842142  MAUZAN CAT HOUSE

In [ ]:
def longitude_function(row):
  return row.replace(' ','').split(',')[1]

def latitude_function(row):
  return row.replace(' ','').split(',')[0]

In [ ]:
data_user_copy['longitude'] = data_user_copy['latitude'].apply(lambda row: longitude_function(row))
data_user_copy['latitude'] = data_user_copy['latitude'].apply(lambda row: latitude_function(row))

In [ ]:
data_user_copy

jenis_hewan                                        alamat_user  \
0        Kucing  Malaingkedi, Sorong Utara, Malaingkedi, Kec. S...   
1        Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
2        Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
3        Kucing  Malaingkedi, Sorong Manoi, Sorong City, West P...   
4        Kucing  Jl. Tj. Dofior, Malaingkedi, Kec. Sorong Utara...   
..          ...                                                ...   
514      Anjing  Tarafu, Murhum, Bau-Bau City, South East Sulaw...   
515      Anjing  Jl. Erlangga No.32, Lanto, Kec. Murhum, Kota B...   
516      Anjing  Jl. Laode Walanda No.19, Wameo, Kec. Murhum, K...   
517      Anjing  Jl. Dr. Wahidin No.88, Lamangga, Kec. Murhum, ...   
518      Anjing  Jl. Dr. Wahidin, Lamangga, Kec. Murhum, Kota B...   

                latitude          nama_shelter           longitude  
0    -0.8794857742573828      MAUZAN CAT HOUSE   131.2980475555453  
1     -0.878624210533688      MAUZAN CAT HOUSE   131.2977266651048  
2    -0.8780682204151269      MAUZAN CAT HOUSE   131.2979108467057  
3    -0.8774857465062342      MAUZAN CAT HOUSE  131.29741346457152  
4    -0.8813631850780076      MAUZAN CAT HOUSE  131.30094486842142  
..                   ...                   ...                 ...  
514   -5.461069551795686  Buton Petshop & Care  122.59559061146419  
515   -5.461299147671692  Buton Petshop & Care  122.59676400660457  
516   -5.462613582363002  Buton Petshop & Care  122.59748764840758  
517  -5.4656093675169934  Buton Petshop & Care  122.59753707778708  
518   -5.466141406064901  Buton Petshop & Care  122.59906476571034  

[519 rows x 5 columns]

In [ ]:
data_user_copy = data_user_copy[['jenis_hewan','alamat_user','latitude','longitude','nama_shelter']]

In [ ]:
data_user_copy.head()

jenis_hewan                                        alamat_user  \
0      Kucing  Malaingkedi, Sorong Utara, Malaingkedi, Kec. S...   
1      Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
2      Kucing  Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ...   
3      Kucing  Malaingkedi, Sorong Manoi, Sorong City, West P...   
4      Kucing  Jl. Tj. Dofior, Malaingkedi, Kec. Sorong Utara...   

              latitude           longitude      nama_shelter  
0  -0.8794857742573828   131.2980475555453  MAUZAN CAT HOUSE  
1   -0.878624210533688   131.2977266651048  MAUZAN CAT HOUSE  
2  -0.8780682204151269   131.2979108467057  MAUZAN CAT HOUSE  
3  -0.8774857465062342  131.29741346457152  MAUZAN CAT HOUSE  
4  -0.8813631850780076  131.30094486842142  MAUZAN CAT HOUSE

In [ ]:
test_user = data_user.copy()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
test_user['nama_shelter'] = le.fit_transform(test_user['nama_shelter'])

In [ ]:
np.unique(data_user['nama_shelter'])

array(['AKM HOUSE', "Burney D'cat", 'Buton Petshop & Care',
       'Cat House Ajukir', 'Kenanga Cattery', 'MAUZAN CAT HOUSE',
       'My Home My Animals Haven', 'Pasar Hobi',
       'Ragdoll Cat House Makassar', 'Sehati Animal Sanctuary',
       "Sugar glider home's", 'The kitten cattery',
       "Yahya Makassar Pet's", 'Yayasan pecinta hewan Dumai (pandu)',
       'chewyloky cathouse'], dtype=object)

In [ ]:
np.unique(test_user['nama_shelter'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
test_user

alamat_user  latitude   longitude  \
0    Malaingkedi, Sorong Utara, Malaingkedi, Kec. S... -0.879486  131.298048   
1    Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ... -0.878624  131.297727   
2    Jl. F Kalasuat, Malaingkedi, Kecamatan Sorong ... -0.878068  131.297911   
3    Malaingkedi, Sorong Manoi, Sorong City, West P... -0.877486  131.297413   
4    Jl. Tj. Dofior, Malaingkedi, Kec. Sorong Utara... -0.881363  131.300945   
..                                                 ...       ...         ...   
514  Tarafu, Murhum, Bau-Bau City, South East Sulaw... -5.461070  122.595591   
515  Jl. Erlangga No.32, Lanto, Kec. Murhum, Kota B... -5.461299  122.596764   
516  Jl. Laode Walanda No.19, Wameo, Kec. Murhum, K... -5.462614  122.597488   
517  Jl. Dr. Wahidin No.88, Lamangga, Kec. Murhum, ... -5.465609  122.597537   
518  Jl. Dr. Wahidin, Lamangga, Kec. Murhum, Kota B... -5.466141  122.599065   

    jenis_hewan  nama_shelter  
0        Kucing             5  
1        Kucing             5  
2        Kucing             5  
3        Kucing             5  
4        Kucing             5  
..          ...           ...  
514      Anjing             2  
515      Anjing             2  
516      Anjing             2  
517      Anjing             2  
518      Anjing             2  

[519 rows x 5 columns]